// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCASm5otwQMh5neXKdFV9RoOAYYcS3f5_o',
    appId: '1:892544939021:web:554d9bc7dcb6db6a439144',
    messagingSenderId: '892544939021',
    projectId: 'dhiasehaim-55f42',
    authDomain: 'dhiasehaim-55f42.firebaseapp.com',
    storageBucket: 'dhiasehaim-55f42.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU7ajsqTe82-YvcnXZWHjF-V8lGo-MYII',
    appId: '1:892544939021:android:a78a6a8de998d9a3439144',
    messagingSenderId: '892544939021',
    projectId: 'dhiasehaim-55f42',
    storageBucket: 'dhiasehaim-55f42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3nJhSw056rXMZwcjxvGMfuu6gAb74L3w',
    appId: '1:892544939021:ios:23bba8a3cb09faa2439144',
    messagingSenderId: '892544939021',
    projectId: 'dhiasehaim-55f42',
    storageBucket: 'dhiasehaim-55f42.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3nJhSw056rXMZwcjxvGMfuu6gAb74L3w',
    appId: '1:892544939021:ios:23bba8a3cb09faa2439144',
    messagingSenderId: '892544939021',
    projectId: 'dhiasehaim-55f42',
    storageBucket: 'dhiasehaim-55f42.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCASm5otwQMh5neXKdFV9RoOAYYcS3f5_o',
    appId: '1:892544939021:web:317bb036f1b7a05e439144',
    messagingSenderId: '892544939021',
    projectId: 'dhiasehaim-55f42',
    authDomain: 'dhiasehaim-55f42.firebaseapp.com',
    storageBucket: 'dhiasehaim-55f42.appspot.com',
  );
}
